services:
  app:
    image: node:18.18
    container_name: resume-L1

    stdin_open: true
    tty: true

    env_file:
      - .env
      - .env.local

    ports:
      - 3005:3000

    volumes:
      - ./src/L1/resume:/home

    working_dir: /home

    command: "/bin/bash"

    
