services:
  workrpy:
    build: 
      context: ./python
      dockerfile: Dockerfile
    image: resume-worker-python
    container_name: resume-worker-python

    stdin_open: true
    tty: true

    env_file:
      - .env
      - .env.local

    volumes:
      - .:/home

    working_dir: /home

    command: "/bin/bash"

  workr:
    build: 
      context: ./R
      dockerfile: dockerfile
    image: resume-worker
    container_name: resume-worker

    stdin_open: true
    tty: true

    env_file:
      - .env
      - .env.local

    volumes:
      - .:/home

    working_dir: /home

    command: "/bin/bash"
   

  app:
    image: node:18.18
    container_name: resume-L1

    stdin_open: true
    tty: true

    env_file:
      - .env
      - .env.local

    ports:
      - 3005:3000

    volumes:
      - ./src/L1/resume:/home

    working_dir: /home

    command: "/bin/bash"

  app-test:
    image: node:18.18
    container_name: resume-L1-test

    stdin_open: true
    tty: true

    env_file:
      - .env
      - .env.local

    volumes:
      - ./src/L1/resume:/home

    working_dir: /home

    command: "sh -c 'npm install && npm test'"

    
