import type { Metadata } from "next";
import { Inter, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import ClientProvider from '../lib/ClientProvider'; // 先ほど作成したClientProviderをインポート
import { SearchItemProvider } from './contexts/SearchItemsProvider';
import { Header } from './components/Header'
import { Suspense } from "react";

// 使用したいフォントの設定
const noto = Noto_Sans_JP({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
});

const inter = Inter({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <Suspense>
        <SearchItemProvider>
            <body className={noto.className}>
              <div className="flex flex-col gap-10">
                <Header />
                <main className="">{children}</main>
              </div>
            </body>
        </SearchItemProvider>
</Suspense>
      </ClientProvider>
    </html>
  );
}
