name: Get e-Stat Data

on:
  schedule:
    - cron: '0 4 * * *' # 毎日 0:00(JST) に実行
  workflow_dispatch:

jobs:

  getter:
    runs-on: ubuntu-latest
    env:
      APPID: ${{ secrets.APPID_ESTATAPI }}
      PG_DATABSE_URL: ${{ secrets.PG_DATABSE_URL }}
      ROOT_DIR: ./resource
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2' # The R version to download (if necessary) and use.
          # Use "renv" to retrieve R version recorded in renv.lock file.

      - name: Install packages
        uses: r-lib/actions/setup-renv@v2

      - name: Run R script for Get e-Stat Data
        run:  Rscript ./R/getter.R $ROOT_DIR


      - name: Run R script for Get e-Stat Data
        run:  ls ./resource -R -all

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $ROOT_DIR
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "resource update [bot] "
          fi
  
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main      