name: Get and Register for e-Stat Data

on:
  schedule:
    - cron: '0 4 * * *' # 毎日 0:00(JST) に実行
  workflow_dispatch:

jobs:

  getter:
    uses: ./.github/workflows/getter.yaml

  # register:
  #   needs: getter
  #   uses: ./.github/workflows/register.yaml

